version: '3.5'
services:

  pg14:
    image: kilfu0701/docker-postgres:${TAG}
    build: .
    container_name: pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./volume/postgresql/data:/var/lib/postgresql/data
    #command: tail -f /dev/null

networks:
  default:
    name: 'pg14'
